name: Application Test Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  checkout-and-haxe-set:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # リポジトリを$GITHUB_WORKSPACEでチェックアウトし、ジョブがアクセスできるようにします。
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
      # Runs a set of commands using the runners shell
  setup-haxelib:
    needs: checkout-and-haxe-set
    strategy:
      matrix:
        include: 
          - target: windows
            runs-on: windows-latest
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Windows Install Haxelib
        if: ${{ matrix.target == 'windows' }}
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > /dev/null --quiet
          .\"setup/windows.bat"
        shell: cmd
      - name: Skip SScript setup mode
        if: ${{ matrix.target == 'windows' }}
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> %USERPROFILE%/settings.cocoa
        shell: cmd
  build:
    needs: setup-haxelib
    strategy:
      matrix:
        os: [windows]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build ${{ matrix.os }} --app-version="4.0.0-${{ github.run_id}}"  -D officialBuild
      - name: Publish Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: Funkin' HorizonAnimEditor-${{ matrix.os }}
          path: build/flixel/release/${{ matrix.os }}/bin
          retention-days: 3
